import type {ImageSourcePropType} from 'react-native';

export const imageResources: Record<string, ImageSourcePropType> = {
  '1': require('@/assets/images/1.jpg'),
  '2': require('@/assets/images/2.jpg'),
  '3': require('@/assets/images/3.jpg'),
  '4': require('@/assets/images/4.jpg'),
  '5': require('@/assets/images/5.jpg'),
  '6': require('@/assets/images/6.jpg'),
  '7': require('@/assets/images/7.jpg'),
  '8': require('@/assets/images/8.jpg'),
  '9': require('@/assets/images/9.jpg'),
  '10': require('@/assets/images/10.jpg'),
  '11': require('@/assets/images/11.jpg'),
  '12': require('@/assets/images/12.jpg'),
  '13': require('@/assets/images/13.jpg'),
  '14': require('@/assets/images/14.jpg'),
  '15': require('@/assets/images/15.jpg'),
  '16': require('@/assets/images/16.jpg'),
  '17': require('@/assets/images/17.jpg'),
  '18': require('@/assets/images/18.jpg'),
  '19': require('@/assets/images/19.jpg'),
  '20': require('@/assets/images/20.jpg'),
  '21': require('@/assets/images/21.jpg'),
  '22': require('@/assets/images/22.jpg'),
  '23': require('@/assets/images/23.jpg'),
  '24': require('@/assets/images/24.jpg'),
};
